version: "3"

services:

    shopware:
      image: dockware/dev:6.4.9.0
      container_name: my_shop
      volumes:
         - "./src/custom/plugins/MyPlugin:/var/www/html/custom/plugins/MyPlugin"
      ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"
      networks:
         - web
      environment:
         - XDEBUG_ENABLED=1

networks:
  web:
    external: false
